// Loads the bundled, compact Dota 2 VScript API (generated by scripts/build-api.mjs).

import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { pathExists } from "../util/fsx.js";

export interface ApiArg {
  name: string;
  type: string;
  description?: string;
}

export interface ApiFunction {
  name: string;
  signature: string;
  args: ApiArg[];
  returns: string;
  description?: string;
  available?: "server" | "client" | "both";
}

export interface ApiClass {
  name: string;
  clientName?: string;
  extends?: string;
  description?: string;
  methods: ApiFunction[];
}

export interface ApiEnumMember {
  name: string;
  value?: number | string;
  description?: string;
}

export interface ApiEnum {
  name: string;
  kind: "enum" | "constant";
  value?: number | string;
  available?: string;
  members?: ApiEnumMember[];
}

export interface ApiData {
  classes: ApiClass[];
  functions: ApiFunction[];
  enums: ApiEnum[];
  generatedAt?: string;
}

let cache: ApiData | undefined;

async function findDataFile(): Promise<string> {
  const here = dirname(fileURLToPath(import.meta.url));
  // Walk up to the package root (the dir containing package.json) and look in src/data,
  // then fall back to a dist/data copy if one exists.
  let dir = here;
  for (let i = 0; i < 6; i++) {
    if (await pathExists(join(dir, "package.json"))) {
      const candidates = [
        join(dir, "src", "data", "dota-api.json"),
        join(dir, "dist", "data", "dota-api.json"),
        join(dir, "data", "dota-api.json"),
      ];
      for (const c of candidates) if (await pathExists(c)) return c;
    }
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  throw new Error(
    "Bundled API data (src/data/dota-api.json) not found. Run `npm run build:api` to generate it.",
  );
}

export async function loadApi(): Promise<ApiData> {
  if (cache) return cache;
  const file = await findDataFile();
  cache = JSON.parse(await readFile(file, "utf8")) as ApiData;
  return cache;
}
