// Loads the bundled, compact Dota 2 VScript API (generated by scripts/build-api.mjs).

import { readFile } from "node:fs/promises";
import { resolveDataPath } from "../util/datapath.js";

export interface ApiArg {
  name: string;
  type: string;
  description?: string;
}

export interface ApiFunction {
  name: string;
  signature: string;
  args: ApiArg[];
  returns: string;
  description?: string;
  available?: "server" | "client" | "both";
}

export interface ApiClass {
  name: string;
  clientName?: string;
  extends?: string;
  description?: string;
  methods: ApiFunction[];
}

export interface ApiEnumMember {
  name: string;
  value?: number | string;
  description?: string;
}

export interface ApiEnum {
  name: string;
  kind: "enum" | "constant";
  value?: number | string;
  available?: string;
  members?: ApiEnumMember[];
}

export interface ApiData {
  classes: ApiClass[];
  functions: ApiFunction[];
  enums: ApiEnum[];
  generatedAt?: string;
}

let cache: ApiData | undefined;

export async function loadApi(): Promise<ApiData> {
  if (cache) return cache;
  const file = await resolveDataPath("dota-api.json");
  cache = JSON.parse(await readFile(file, "utf8")) as ApiData;
  return cache;
}
